### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by nicain** [AllenInstitute/neuroglia#45]
* neuroglia version: b20ee5cb1db36423b05f7ea898e64de6140d3bd0
* Python version: 2.7
* Operating System: Ubuntu 16.04.2

### Description

Looks like test rule needs to be fixed

### What I Did

tried to `run make test `, received:
```
make test
test.sh
make: test.sh: Command not found
Makefile:2: recipe for target 'test' failed
make: *** [test] Error 127
```

**Comment by neuromusic** [comment]
@mochic feel free to close this issue if it is no longer relevant
